//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODTCONVERT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODTCONVERT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string BottomText {
            get {
                return ResourceManager.GetString("BottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is ready.
        /// </summary>
        public static string DocumentReadyText {
            get {
                return ResourceManager.GetString("DocumentReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully saved.
        /// </summary>
        public static string DocumentSavedText {
            get {
                return ResourceManager.GetString("DocumentSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftText {
            get {
                return ResourceManager.GetString("LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have not found any file by this path. Maybe you have deleted it? Anyway, try loading something else!.
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page margins.
        /// </summary>
        public static string PageMarginsText {
            get {
                return ResourceManager.GetString("PageMarginsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        public static string PageSizeText {
            get {
                return ResourceManager.GetString("PageSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string RecentText {
            get {
                return ResourceManager.GetString("RecentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RightText {
            get {
                return ResourceManager.GetString("RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the path to active document.
        /// </summary>
        public static string SourcePathText {
            get {
                return ResourceManager.GetString("SourcePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODT - PDF converter.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopText {
            get {
                return ResourceManager.GetString("TopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re doomed! Something wrong have happened and we do not know what it is. Please contact program&apos;s developer..
        /// </summary>
        public static string UnknownProblemText {
            get {
                return ResourceManager.GetString("UnknownProblemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start your work, please press the button with blank document icon and select an ODT file to work with. Its contents will be shown here..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODT file you have provided has wrong syntax and therefore is unreadable. Try loading something else!.
        /// </summary>
        public static string WrongFormatText {
            get {
                return ResourceManager.GetString("WrongFormatText", resourceCulture);
            }
        }
    }
}
